import {
  Activity,
  BarChart3,
  BookOpen,
  Bot,
  Building2,
  CalendarDays,
  Cog,
  CreditCard,
  DollarSign,
  FlaskConical,
  Flag,
  Globe,
  History,
  Home,
  Inbox,
  type LucideIcon,
  Megaphone,
  Percent,
  Plug,
  RefreshCcw,
  Rocket,
  Settings,
  ShoppingCart,
  Target,
  Ticket,
  Users,
  Workflow,
} from "lucide-react";

export const NAV_ICONS: Record<string, LucideIcon> = {
  "/dashboard": Home,
  "/dashboard/inbox": Inbox,
  "/dashboard/contacts": Users,
  "/dashboard/leads": Target,
  "/dashboard/orders": ShoppingCart,
  "/dashboard/appointments": CalendarDays,
  "/dashboard/ai-employee": Bot,
  "/dashboard/knowledge-base": BookOpen,
  "/dashboard/test-ai": FlaskConical,
  "/dashboard/automations": Workflow,
  "/dashboard/analytics": BarChart3,
  "/dashboard/website": Globe,
  "/dashboard/integrations": Plug,
  "/dashboard/campaigns": Megaphone,
  "/dashboard/ads": Rocket,
  "/admin": Home,
  "/admin/workspaces": Building2,
  "/admin/plans": CreditCard,
  "/admin/coupons": Percent,
  "/admin/refunds": RefreshCcw,
  "/admin/revenue": DollarSign,
  "/admin/platform-analytics": BarChart3,
  "/admin/ai-usage": Bot,
  "/admin/ai-operations": Cog,
  "/admin/tickets": Ticket,
  "/admin/feature-flags": Flag,
  "/admin/system-health": Activity,
  "/admin/settings": Settings,
  "/admin/admins": Users,
  "/admin/audit-log": History,
};
